/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed": "#2d1505",
        "on-background": "#191c1d",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcbd",
        "secondary-fixed": "#ffdbc7",
        "on-surface": "#191c1d",
        "surface-dim": "#d9dadb",
        error: "#ba1a1a",
        primary: "#005ea1",
        secondary: "#795741",
        "on-error": "#ffffff",
        "surface-tint": "#0461a5",
        "secondary-container": "#ffd1b5",
        "on-tertiary-fixed-variant": "#693c00",
        "on-primary-container": "#fcfbff",
        "surface-variant": "#e1e3e4",
        outline: "#717782",
        "on-primary-fixed-variant": "#00497f",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a86400",
        surface: "#f8f9fa",
        "tertiary-fixed-dim": "#ffb86d",
        "surface-container": "#edeeef",
        "on-surface-variant": "#414751",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed": "#d2e4ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5f402b",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#a0c9ff",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-container": "#fffaff",
        "inverse-primary": "#a0c9ff",
        "surface-container-high": "#e7e8e9",
        tertiary: "#864e00",
        "on-primary-fixed": "#001c37",
        background: "#f8f9fa",
        "primary-container": "#2f77bd",
        "on-secondary-container": "#7a5742",
        "secondary-fixed-dim": "#eabda2",
        "outline-variant": "#c1c7d2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        header_height: "60px",
        footer_height: "48px",
        gutter: "24px",
        margin_page: "40px",
        container_max_width: "1200px",
        stitch_gap: "4px",
        content_height: "calc(100vh - 60px - 48px)",
      },
      maxWidth: {
        container_max_width: "1200px",
      },
      fontFamily: {
        "headline-xl-mobile": ["Noto Sans KR", "sans-serif"],
        "headline-md": ["Noto Sans KR", "sans-serif"],
        "headline-lg": ["Noto Sans KR", "sans-serif"],
        "body-md": ["Noto Sans KR", "sans-serif"],
        "headline-xl": ["Noto Sans KR", "sans-serif"],
        "body-lg": ["Noto Sans KR", "sans-serif"],
        "label-sm": ["Noto Sans KR", "sans-serif"],
      },
      fontSize: {
        "headline-xl-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
